services:
  postgres:
    image: postgres:17-alpine
    container_name: cp-bowl-db
    environment:
      - POSTGRES_USER=bowl_user
      - POSTGRES_PASSWORD=bowl_pass
      - POSTGRES_DB=cp_bowl
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: