services:
  - type: web
    name: chilli-pickles-bowl-app
    runtime: java
    buildCommand: ./gradlew :frontend:build :backend:build
    startCommand: java -jar backend/build/libs/backend-0.0.1.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: bowl-db
          property: connectionString
      - key: NODE_VERSION
        value: 22.11.0

databases:
  - name: bowl-db
    databaseName: cp_bowl
    user: bowl_user
    plan: free